version: '3.8'

services:
  app:
    image: choyeseol07/ipsidori:latest
    container_name: ipsidori
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
