spring:
  application:
    name: dori
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 30
        format_sql: true
        jdbc.time_zone: Asia/Seoul
        show_sql: true
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
