name: Deploy to AWS EC2 using Docker

on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE_NAME: ${{  secrets.DOCKER_HUB_USERNAME  }}/ipsidori
  SERVER_HOST: ${{  secrets.EC2_HOST  }}
  SERVER_USER: ${{  secrets.EC2_USER  }}
  SERVER_PASSWORD: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.CONFIG_SUBMODULE_TOKEN}}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Pull the existing Docker image (if any)
        run: |
          docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest || true

      - name: Build the Docker image with cache
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest \
          --cache-from=${{ env.DOCKER_IMAGE_NAME }}:latest \
          --platform linux/amd64

      - name: Login to Docker Hub using Access Token
        run: |
          echo ${{ env.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push ${{env.DOCKER_IMAGE_NAME}}:latest

  deploy-to-ec2:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_PASSWORD }}
          port: 22
          script: |
            # docker-project 디렉토리로 이동
            cd docker-project

            # 최신 백엔드 이미지 pull
            sudo docker pull ${{env.DOCKER_IMAGE_NAME}}:latest

            # 기존 백엔드 컨테이너만 정리 (인프라는 유지)
            sudo docker stop ipsidori || true
            sudo docker rm ipsidori || true

            # docker-compose로 인프라 서비스 실행 (네트워크 자동 생성)
            sudo docker-compose up -d

            # 백엔드 컨테이너 실행 (기존 네트워크 사용)
            sudo docker run -d \
              --name ipsidori \
              --network ipsidori_default \
              -p 8080:8080 \
              --env-file ./.env \
              --restart always \
              ${{env.DOCKER_IMAGE_NAME}}:latest
